name: vue-deploy

on:
  push:
    branches:    
      - master

jobs:
  vue-deploy:

    runs-on: ubuntu-latest

    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:10
      - name: use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      # npm install
      - name: npm install and build
        run: |
          npm install
          npm run build
        env:
          CI: true
      # Deploy
      - name: deploy
        uses: easingthemes/ssh-deploy@v2.0.8
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          REMOTE_HOST: "129.211.92.44"
          REMOTE_USER: "root"
          REMOTE_PORT: "22"
          SOURCE: "./dist/"
          TARGET: "/usr/local/nginx/html/h5"
          ARGS: "-avz --delete"
          
